[package]
name = "scanner_air"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
threadpool = "1.8.1"
futures = "0.3"